name: Android CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1
      
    - name: Make Gradle Wrapper Executable
      run: chmod +x ./apps/android/gradlew
      
    - name: Build Debug APK
      run: |
        cd apps/android
        ./gradlew assembleDebug --stacktrace --no-daemon
        
    - name: Run Tests
      run: |
        cd apps/android
        ./gradlew testDebugUnitTest --stacktrace --no-daemon
        
    - name: Static Analysis
      run: |
        cd apps/android
        ./gradlew lintDebug --stacktrace --no-daemon
        
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: apps/android/app/build/outputs/apk/debug/
        retention-days: 7

  json-validation:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Validate JSON Files
      run: |
        echo "Validating JSON files..."
        
        # Simple JSON validation without complex Python formatting
        for file in packages/shared-data/src/*.json; do
          if python3 -c "import json; json.load(open('$file'))" 2>/dev/null; then
            echo "✓ $(basename $file) is valid"
          else
            echo "✗ $(basename $file) is invalid"
            exit 1
          fi
        done
        
        echo "All JSON files validated successfully! ✅"

  kotlin-analysis:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Make Gradle Wrapper Executable
      run: chmod +x ./apps/android/gradlew  # ADDED THIS LINE
        
    - name: Kotlin Compilation Check
      run: |
        cd apps/android
        ./gradlew compileDebugKotlin --stacktrace --no-daemon --continue
