name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  detekt:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Make Gradle Wrapper Executable
      run: chmod +x ./apps/android/gradlew  # FIXED PATH
      
    - name: Run Detekt
      run: |
        cd apps/android
        ./gradlew detekt --stacktrace --no-daemon
        
  ktlint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Make Gradle Wrapper Executable
      run: chmod +x ./apps/android/gradlew  # FIXED PATH
        
    - name: Run ktlint
      run: |
        cd apps/android
        ./gradlew ktlintCheck --stacktrace --no-daemon

  dependency-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Make Gradle Wrapper Executable
      run: chmod +x ./apps/android/gradlew  # FIXED PATH
        
    - name: Check dependencies
      run: |
        cd apps/android
        ./gradlew app:dependencies --configuration debugCompileClasspath > dependencies.txt
        echo "Dependencies exported to dependencies.txt"
