name: F-Droid Build Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  fdroid-build:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[fdroid]') || github.event_name == 'push'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Build F-Droid Variant
      run: |
        cd apps/android
        ./gradlew assembleFdroidDebug --stacktrace --no-daemon
        
    - name: Check F-Droid Compliance
      run: |
        echo "Checking F-Droid compliance..."
        
        # Check for Google Play Services
        if grep -r "com.google.android.gms" apps/android/; then
          echo "❌ Google Play Services detected in F-Droid variant"
          exit 1
        fi
        
        # Check for proprietary libraries
        if grep -r "com.google.firebase" apps/android/; then
          echo "❌ Firebase detected in F-Droid variant"
          exit 1
        fi
        
        echo "✅ F-Droid compliance check passed"
        
    - name: Upload F-Droid APK
      uses: actions/upload-artifact@v4
      with:
        name: fdroid-apk
        path: apps/android/app/build/outputs/apk/fdroid/debug/
        retention-days: 7
