name: F-Droid Build Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  fdroid-build:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[fdroid]') || github.event_name == 'push'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Make Gradle Wrapper Executable
      run: chmod +x ./apps/android/gradlew  # FIXED PATH
        
    - name: Build F-Droid Variant
      run: |
        cd apps/android
        ./gradlew assembleFdroidDebug --stacktrace --no-daemon
        
    - name: Check F-Droid Compliance
      run: |
        echo "Checking F-Droid compliance..."
        
        # Check for Google Play Services in F-Droid source
        if grep -r "com.google.android.gms" apps/android/app/src/fdroid/; then
          echo "❌ Google Play Services detected in F-Droid source"
          exit 1
        fi
        
        # Check for proprietary libraries in F-Droid source
        if grep -r "com.google.firebase" apps/android/app/src/fdroid/; then
          echo "❌ Firebase detected in F-Droid source"
          exit 1
        fi
        
        # Check build.gradle for F-Droid specific dependencies
        if grep -A 10 -B 10 "fdroid" apps/android/app/build.gradle.kts | grep -E "com.google.android.gms|com.google.firebase"; then
          echo "❌ Proprietary dependencies in F-Droid build configuration"
          exit 1
        fi
        
        echo "✅ F-Droid compliance check passed"
        
    - name: Upload F-Droid APK
      uses: actions/upload-artifact@v4
      with:
        name: fdroid-apk
        path: apps/android/app/build/outputs/apk/fdroid/debug/
        retention-days: 7
